name: MSBuild Release

on: [pull_request, push]

env:
  # Ruta al archivo .sln relativo a la raíz del proyecto
  SOLUTION_FILE_PATH: Horion.sln

  # Tipo de configuración
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restaurar paquetes NuGet
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Compilar solución
      run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE_PATH }}

    - name: Subir artefacto DLL
      uses: actions/upload-artifact@v4
      with:
        name: HorionRelease
        path: ./x64/Release/Horion.dll
